import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import NavBar from "./navbar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Ma Bibliothèque",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col dark:bg-gray-800 min-h-screen`}
        >
        <header>
            <NavBar/>
        </header>

        <main className="flex flex-col flex-grow text-center mx-auto p-4 items-center justify-center">
            {children}
        </main>

        <footer className="container mx-auto p-4">
            <h2 className="dark:text-gray-100">
                The Footer
            </h2>
        </footer>
        </body>
        </html>
    );
}
